### ISSUE TITLE
What does this code do?

### ISSUE THREAD

**Issue by winchell-jeff** [JacksonMaxfield/cue-queue#12]
I can't find any instructions on how to use this. From looking at the docs, I assume it does not output segments of a text. Does it?

**Comment by JacksonMaxfield** [comment]
This codebase is still under development and I just haven't had a lot of time to work on it recently. More to come soon.

The language around this repo should be cleaned up, the goal of this work is to align sentences to minutes.

While it's not ready for use yet the end goal is: given some transcript of sentences, and some list of minutes items, map each sentence to a minutes item.

**Comment by JacksonMaxfield** [comment]
When this codebase is ready for use there will be a quickstart on the README. For now, I will mark on the README that this is under development.

**Comment by TheSecurityDev** [comment]
Any updates on this? I can't tell whether this is something I can use or not without having some examples or a quickstart.

**Comment by JacksonMaxfield** [comment]
I will update the README to say: "This library isn't ready, ignore and try to find a different one."
